name: Node.js CI/CD

on: 
  push:
    branches: ["staging"]

jobs: 
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setting up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: |
        touch .env
        echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env
        echo "PORT=${{ secrets.PORT }}" >> .env